{% set name = "shed" %}
{% set version = "0.7.2" %}
{% set sha256 = "ad9397ec2ef106eb7c2ddda40a7e029326f99a19e4a4d5dabf990cf2447d7025" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/releases/download/{{ version }}/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - rapidz
    - numpy
    - scipy
    - matplotlib
    - databroker
    - bluesky
    - event-model
    - networkx >=2.0
    - xonsh

test:
  imports:
    - shed
    - shed.translation

about:
  home: https://github.com/xpdAcq/SHED
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Streaming Heterogeneous Event Data'
  doc_url: https://xpdacq.github.io/SHED/ 
  dev_url: https://github.com/xpdAcq/SHED

extra:
  recipe-maintainers:
    - CJ-Wright
