{% set name = "shed" %}
{% set version = "0.3.0" %}
{% set sha256 = "df4a7fec70955fbf807e8a1956dd46cc1317e6dd77c91105b337bf61b17eb996" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - streamz_ext
    - numpy
    - scipy
    - matplotlib
    - databroker
    - bluesky
    - event-model
    - networkx >=2.0

test:
  imports:
    - shed
    - shed.translation

about:
  home: https://github.com/xpdAcq/SHED
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Streaming Heterogeneous Event Data'
  doc_url: https://xpdacq.github.io/SHED/ 
  dev_url: https://github.com/xpdAcq/SHED

extra:
  recipe-maintainers:
    - CJ-Wright
