travis:
  secure:
    BINSTAR_TOKEN: NFN3uG9fAnW1UDuR5R3AJ/FNH8Rla23xH+Rsf9NEc7VGRu3dC5ehxSmtAVZX7oBQfFVmJd86RdU6hkV+PAjoH0orgbv2n3bE0EBl3ZNtQV3BEVnBh5eRGahYV/sc1fjvtnnxqGu3AVhaxRhihtoQRHwykpR179J9OWh5DkESml7WfNanQVsMbMYeQ1EQQDR0cmlDElilbfE/MwXkG10KSoqt+ZH1nGeg+QqsnMuKBWByfnIMIHkyWTFTwEZSppP4Fx9g02Czh0azWEtsFxPVCWAVgFB1LPuKtrJouwsXUHMhLhmlEL5YPdTYLCs8zOzIHWQBEBagsugdHNQ0bncLdWmqDGQhM9WmD7s4V7TrJERrOzMrANlULPmUREnRZx3Kd+s+iiGB9htdf3jJ/AKg8t3pxOO+o29pr1PN+7JVuoW8wZlBLQhT/c/KY9BTS0EARDsTfm+iUG3ZnE5pH+QWny3wUc55DyQdx0ji8/ZyI/9mm2aaF3i/DBYP85ID5xJ0+gmNel9zk2cTjJUeJ+chnrTHSOfWb8PChK1NIirsTaeTPjWB8lAFwK1bTRR8og0Nu/x9LlIplpQzucBr1UtQwZN9Smya1XnQimujp1nVp4yi1kj7pXF/9g+dOLP1AIf7A0YQdu8vfmXzazvd61eA9a6xKn/BqmKi7mt9RDnyLc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
